site_name: PyHBR Docs

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [src]

markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.details
- pymdownx.snippets
- pymdownx.superfences
- admonition

nav:
  - 'index.md'
  - 'design.md'
  - 'arc_hbr.md'
  - 'reference.md'

watch:
- src

theme:
  name: "material"