= BHF HBR Bleeding/Ischaemia Risk Tool (UHBW)
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

This repository contains development information related to a high-bleeding-risk/high-ischaemia-risk tool intended to guide antithrombotic therapy choices in ACS patients.

The repository contains these items:

* *Project Description:* The file `risk_management_file.pdf`, which describes the purpose of the tool. The source code is stored in the folder `risk_management_file/`
* *Project Code:* A python package `pyhbr` (under development), containing all the code/model-development/analysis for this project. The documentation for this package is hosted https://jrs0.github.io/hbr_uhbw/[here].
* *Analysis/Modelling Scripts:* A folder `scripts/`, containing (work-in-progress) scripts that use `pyhbr`. The `prototypes/` folder contains code that is more related to testing/development.