project:
  output-dir: _output
  render: 
    - icb_basic_report_gen.qmd

execute:
  echo: false
  warning: false
  error: true

engine: jupyter
jupyter: python3

date: now
date-format: short
author: John Scott

toc: true
number-sections: true
bibliography: ../risk_management_file/ref.bib  
  
