= Intended Purpose

The intended purpose of the device is a description of how it is intended to be used, how it should behave, who should use it, and other high-level information. Design/implementation choices should be guided by how well they meet the intended purpose.

== Function of the device

The purpose of the tool is to help clinicians identify the relative risks of bleeding outcomes and ischaemic outcomes for patients presenting with acute coronary syndromes (ACS), for the purpose of choosing between different therapy options.

Currently stratified risk scores do exist but, anecdotally, are not routinely used in the evaluation of patients initiated on anti-coagulation.
Our device would allow for existing risk scores to be used and for the additional use of a machine learning trained device to risk stratify patients. 

For example, if a patient is identified as being at a high risk of bleeding through the use of the tool then the clinician could use this information to choose a less aggressive blood thinning therapy option.

In addition to providing risks on request, the tool should also notify relevant health care professionals if the risks change enough to warrant a change in therapy at any point in a monitoring period.

The tool should be easy enough to use that it can be incorporated into routine clinical practice. This means:

* It should be integrated within current workflows so that it can be routinely used
* It should use information that the clinician is already _required_ to input into clinical systems (it may require existing systems to be modified to require more information to be inputted)
* The amount of required information (or additional required information) should be low enough that a clinician can reasonably source all of it (i.e. the tool cannot require 25 new manually entered data points).

The tool can also use data that is automatically available for an inpatient (i.e. could be automatically drawn from other clinical systems).

== Indications for use

* **Who will use the tool**: clinicians or other health care professionals involved in the assessment of what blood thinning therapy to prescribe to a patient. 
* **When will the tool be used**: when a patient presents with an ACS, and blood thinning therapy is indicated. In addition, any time the risks change and a relevant health-care professional is notified in the monitoring period. It is expected that a healthcare professional would be able to request an automated risk score when requesting other laboratory investigations.
* **What output will the tool give**: any output that indicates a patient's relative bleeding/further ischaemia risk. This could be probabilities from a model, or a simple high/low indicator based on a simple consensus-based calculation. The output from the tool will be decided by choosing from a list of alternative solutions according to (in order of importance):
** which one best meets the intended purpose
** which one is simplest to implement
* **What form will the tool take**: the tool would comprise a risk score subsystem, which would calculate the bleeding/ischaemia risk from patient information, and a supporting process/system for enabling clinicians to obtain the risk scores in accordance with this intended purpose. See [Alternative Forms](alternative_forms.md) for different ways to realise this system.

* **What evidence is required to demonstrate the device meets the specifics of the intended purpose?** 
    * Pre-deployment a review with local and external data would be required. Post deployment an audit of the device risk scores with a selected sample of case reviews to demonstrate whether the scores impact patient management. A retrospective analysis of the number of patients being admitted to hospital post PCI with haemorrhage.
    * A risk management file describing what alternative solutions were considered for all aspects of the design, why the design itself was selected, and how the design is shown to reduce risks/hazards as much as possible in accordance with relevant risk management guidelines.
 
== Reasonably forseeable misuse

* The risk score could be used on the wrong patient group. 
* The risk score could be used to inform choice of the wrong medication (i.e. non-blood-thinning medication) (note: we should explicitly list what medication is within scope?)
* Risks could be interpreted too broadly (i.e. an ischaemia risk targeting only AMI and stroke could be interpreted as applying to all cardiovascular conditions)

