= Weekly Notes

_This section will contain notes about progress this week, specific things to look at in this document (if any), etc._

Summary of previous week work (16th - 23rd Jan 2024):

* Submitted work request to ICB infrastructure to transfer HIC data to ICB, and minimised the HIC tables to avoid duplicating data already at the ICB
* Added summary of ARC criteria to these notes, ahead of looking at calculating as many ARC criteria as possible from the HIC data

Actions for JS this week (23rd - 30th Jan 2024):

* Double check if anything else is needed for UHBW DPIA
* Expect contract from UHBW
* Look into potential submission to ESC conference (submit deadline mid Feb)
* Want to start looking at how to calculate the ARC HBR criteria from HIC, but first need access to the new HIC (hopefully Mike can make it available). 

For Tom to look at:

* In the xref:preexisting_solutions.adoc#arc_hbr_score[ARC Section], #I've highlighted some bits in yellow for you to take a look at#. I'm trying to document the "ideal" ARC HBR calculation for reference, before getting into how to do it using the HIC data

