= List of Currently-Existing Tools/Solutions

This file contains a list of the current solutions to the problems presented in the intended purpose.

== Current Clinical Practice



== Other Risk Scores/Tools

This section contain risk scores (statistical models or other kinds of calculations) designed to aid in the assessment of bleeding/ischaemia risk for ACS patients.

[#arc_hbr_score]
=== ARC HBR Score (applies to assessing high bleeding risk)

_The ARC HBR score is a numerical consensus-based score (rather than being a statistically-driven score), where the presence of a major criterion contributes a 1 to the total score, and a minor criterion contributes 0.5 to the total. A patient is considered at HBR if their score is at least 1 (e.g. due to one major criterion, or two minor criteria)._

==== ARC HBR Score Definition

A summary of the criteria is shown in the table below:

.Summary of ARC HBR criteria
[format=csv, options="header"]
|===
include::arc_hbr_summary.csv[]
|===

The sections below describe the conditions that define each criterion in more detail.

===== Age

Patient age at least 75 at the time of risk score calculation is considered a minor criterion. The relevant time point for the calculation is the time of intervention (the PCI procedure, or shortly afterwords when therapy is being prescribed). 

===== Oral Anticoagulant Use

Anticipated use of long-term OAC is considered a major criterion. There are two types of oral anticoagulants:

* Vitamin K antagonists: warfarin
* Direct oral anticoagulants: apixaban, dabigatran, edoxaban, rivaroxaban

#What timescale defines long-term use?#

===== Chronic Kidney Disease

Severe or end-stage chronic kidney disease (CKD) is a major criterion; moderate CKD is a minor criterion.

The stages of chronic kidney disease map to both ICD-10 codes and estimated glomerular filtration rate measurements (eGFR, from urea and electrolytes laboratory results), as follows (see https://www.nhs.uk/conditions/kidney-disease/diagnosis/[here]):

[cols="1,1,1,1"]
|===
| Stage | ICD-10 | eGFR | ARC-HBR

| Stage 5, end-stage | N18.5 | eGFR < 15 ml/min | Major
| Stage 4, severe | N18.4 | 15 ml/min \<= eGFR < 30 ml/min | Major
| Stage 3b, moderate | N18.3 | 30 ml/min \<= eGFR < 45 ml/min | Minor
| Stage 3a, moderate | N18.3 | 45 ml/min \<= eGFR < 60 ml/min | Minor
| Stage 2, mild | N18.2 | 60 ml/min \<= eGFR < 90 ml/min | None
| Stage 1, normal eGFR | N18.1 | eGFR > 90 ml/min | None
|===

===== Anaemia (Low Haemoglobin)

Haemoglobin level < 11.0 g/dL is a major criterion (for men and women).

Haemoglobin (hb) greater than 11.0 g/dL is divided into two categories:

* Women: 11.0 g/dL \<= hb < 11.9 g/dL is a minor criterion
* Men: 11.0 g/dL \<= hb < 12.9 g/dL is a minor criterion

Any other haemoglobin level is not an ARC HBR criterion.

Haemoglobin level varies with time, and is captured in the data as either laboratory measurements from the full blood count, or potentially as anaemia codes from ICD-10 data in hospital episode statistics.

A blood test including an Hb measurement is often performed in the intervention episode, so this should be used to calculate the risk. If Hb from the index is not available, then a previous low Hb could be taken as a proxy to calculate the risk.

The anaemia HBR criterion has been interpreted to mean baseline anaemia (although this is not explicitly stated in the ARC HBR definition). As a result, the first Hb reading will be used to assess anaemia.

===== Prior Bleeding/Transfusion

#Does what I've written below look right?#

"Spontaneous (nonintracranial) bleeding requiring hospitalization
or transfusion in the past 6 months (or at
any time if recurrent) is considered a major ARC-HBR
criterion, and a first spontaneous (nonintracranial)
bleed requiring hospitalization or transfusion >6 and
<12 months before PCI is considered a minor ARC-HBR
criterion"
-- ARC HBR Paper

Interpretation of terms:

* Spontaneous: not having an obvious cause (like trauma). How would this manifest in hospital records? Primary diagnosis in ICD?
* Recurrent: has occurred at least once before

Summary of criteria:

* **Major**: `A` first bleed not in the brain within 6 months before PCI, which:
** Required hospitalisation (i.e. the hospitalisation was not due to something else) or required transfusion.
** Occurred on its own (i.e. was not caused by something else occurring in the spell, like other procedures)

* **Major** A non-first bleed (recurrent) occurring at any time, which satisfies the requirements above (hospitalisation/transfusion/spontaneous)

* **Minor** A first bleed _not_ within the 6 months before the PCI, which satisfies the requirements above (hospitalisation/transfusion/spontaneous)

===== Thrombocytopenia (Low Platelet Count)

Moderate or severe baseline thrombocytopenia (low platelet count) i, meaning count < 100e9/L, is a major criterion.

Baseline means before intervention. The platelet count can be obtained from measurements from the full blood count. This information is routinely collected in the index presentation.

===== Chronic Bleeding Diatheses

It is a major ARC criteria if any of these conditions are present at PCI:

* Platelet dysfunction (#is this a specific thing?#)
* von Willebrand disease
* Clotting factor deficiencies (including factors VII, VIII [hemophilia A], IX
[hemophilia B], and XI)
* Acquired antibodies to clotting factors (#more detail required?#)
* #Anything else? HBR paper mentions "such as [...] among others" when giving the list above#

===== Cirrhosis with Portal Hypertension

Presence of liver cirrhosis with portal hypertension is a major criterion. #So liver cirrhosis on its own is not a criterion?#

===== Cancer

Diagnosis within the previous 12 months or ongoing active cancer treatment (surgery, radiotherapy, chemotherapy, immunotherapy) is a major ARC criterion.

===== Prior Ischaemic Stroke or ICH

The following are major ARC criteria:

* Brain arteriovenous malformation
* Prior intracranial haemorrhage at any time
* Prior moderate/severe ischaemic stroke (National Institutes of Health Stroke Scale >=5) within 6 months before PCI

The following is a minor criterion

* Prior ischaemic stroke (any severity, any time)

===== Planned Major Non-cardiac Surgery 

Planned non-deferrable major non-cardiac surgery on DAPT after PCI is a major ARC criterion:

Interpretation as follows:

* Timescale after PCI is not relevant. Instead, it is to do with whether the patient will be on DAPT (which has a variable typical timescale after PCI, e.g. 3 - 6months)
* #What constitutes major surgery? Could we make a list of the most common possibilities?#

The calculation depends on a choice of DAPT, so this criteria cannot be calculated automatically based on patient characteristics/history.

===== Prior Major Surgery/Trauma 

Major surgery or major trauma (#what is in these categories?#) within 30 days before PCI is a major ARC criterion.

===== Long-term Oral NSAID/Steroid Use

Planned daily intake of oral NSAID/steriods for >4 d/wk (#what timeframe is this? Looks like days/week, but ARC paper phrases it like a duration#) is a minor ARC criterion.

=== DAPT Score (not directly applicable, but methods may be useful)

_The DAPT score is a linear model whose outcome is a number between -2 and 10, which rates a patient's tendancy to have major ischaemic events (high score) or major bleeding events (low score) if they are continued on therapy after 12 months of major-event-free DAPT. The score is created by combining predictions from separate bleeding and ischaemia models, both run under the assumption of continued vs. discontinued therapy._

* **Intended purpose**: "The App is intended to help physicians determine whether or not to continue or discontinue DAPT in patients at least 12 months post-PCI procedure without having a major bleeding or ischemic event, and who were not on chronic oral anticoagulation" (from https://tools.acc.org/daptriskapp/#!/content/about/about-index[here])
* **Form**: Web calculator requiring the user to input patient risk factors. As these are being inputted, a score from -2 (more bleeding risk) to 9 (more ischaemia risk) rates the trade-off between bleeding and ischaemia risk post 12 months of DATP (see the calculator https://tools.acc.org/daptriskapp/[here]). More detailed information is also shown when the results are submitted, including the actual risk of each event if DAPT is continued vs. discontinued
* **Intended patient group** The calculator should be used only for those patients who have completed 12 months of DAPT already without any major bleeding or ischaemia events

Due to its intended use on patients who have already completed 12 months of DAPT, this tool is not directly comparable with the tool under development, which is supposed to assess patients _before_ they are placed on DAPT. 

Development and validation of the DAPT score is presented in https://pubmed.ncbi.nlm.nih.gov/27022822/[this] paper (full text freely available).

==== Models Used

The following steps were used to build up the model presented in the web calculator

1. One Cox regression model `A` was developed to model time to major bleeding after 12 months
2. Another Cox regression model `B` was developed to model time to major ischaemia event after 12 months

Both these models included variables obtained from literature review and clinical plausibility, and also included the the following variables related to treatment:

* whether continued thienopydidine vs. placebo was used after 12 months (i.e. thienopydidine + aspirin, or aspirin alone)
* whether treatment used clopidogrel or prasugrel (is this independent of the previous point?)

As a result, models A and B can be used to assess differences in risk depending on treatment options.

Next, for each patient:

1. Model `A` was used twice to calculate the increased risk of bleeding, `IncB`, when using thienopyridine + aspirin, vs. using aspirin alone
2. Model `B` was used twice to calculate the reduced risk of ischaemia, `RedI`, when using thienopyridine + aspirin, vs. using aspirin alone
3. Assuming both `IncB` and `RedI` are positive (i.e. the bleeding risk does actually go up with treatment, and the ischaemia risk does actually go down), the paper defines `benefit_risk_difference = RedI - IncB`. Even though they refer to the "absolute" risk difference, I don't think an absolute value is taken, because they refer to negative values. They might mean absolute in the sense of "not relative" (i.e. not a proportion). They interpret high `benefit_risk_difference` as meaning greater benefit of continued therapy, which is consistent with the direction of subtraction above (i.e. `RedI - IncB`, rather than `IncB - RedI`). In this case, a high value comes from "a large reduction in ischaemia risk" and/or a "small increase in bleeding risk". On the other hand, low (or negative) `benefit_risk_difference` comes from a small `RedI` (less reduction in ischaemia risk) and/or a large `IncB` (large increase in bleeding risk), and is therefore interpreted as reduced benefit of continued therapy.

To develop the simple model in the web calculator, the `benefit_risk_difference` was modelled using a linear model, using all the variables used for both models `A` and `B`. As stated in the supplementary material, the coefficients of this model represent the increase in `benefit_risk_difference` (of continuing therapy) for a unit change in the variable. The output of the model is therefore showing risk trade-offs associated with _continuing therapy_ after 12 months, vs. the default case where therapy is stopped (which implicitly corresponds to a `benefit_risk_difference` of zero).

==== Outcomes Modelled

The outcomes used to develop the models `A` and `B` were:

* ischaemia: MI and ARC ST in months 12-30 after ACS (defined in detail in supplementary information)
* bleeding: GUSTO moderate or severe bleeding iv

Detailed information about how each endpoint was defined is contained in the supplementary information. 

==== Predictors used

The predictors are listed in the supplemtary material (eTable 1), and were found through literature review and clinical plausability (this list is the predictors for both bleeding and ischaemia risk):

.Predictors used for models in the DAPT score
[format=csv,options="header"]
|===
include::dapt_predictors.csv[]
|===

==== Validation Used

The methodology to validate the score in the PROTECT trial is described in the supplementary material. In order to assess the score, patients were divided in "high" (score >= 2) and "low" (score < 2) groups. Survival analysis was used to find the hazard ratio for ischaemia between the high and low groups (HR 2.01, meaning a higher score tends to be associated with more ischaemia events), and again for bleeding (HR 0.69, meaning a high score tends to be associated with less major bleeding).

The 

The validation of the two models `A` and `B` used to develop the linear model was not used directly to validate the overall score, because those focus on only one outcome at a time.

