[#arc_hbr_score]
= ARC HBR Score (applies to assessing high bleeding risk)

_The ARC HBR score cite:[urban2019defining] is a numerical consensus-based score (rather than being a statistically-driven score), where the presence of a major criterion contributes a 1 to the total score, and a minor criterion contributes 0.5 to the total. A patient is considered at HBR if their score is at least 1 (e.g. due to one major criterion, or two minor criteria)._

== ARC HBR Score Definition

A summary of the criteria is shown in the table below:

.Summary of ARC HBR criteria
[format=csv, options="header"]
|===
include::arc_hbr_summary.csv[]
|===

The sections below describe the conditions that define each criterion in more detail. The intention is to define an "ideal" ARC HBR calculation, based on the paper, which is amenable to automated calculation by a computer program, and would be possible to achieve if arbitrary information was available to the program. Commentary about ways to enhance the score (possibly increasing its predictive performance), or about practicalities involved in the calculation, are included as notes, but do not form part of the definition of the ideal score.

=== Age

Patient age at least 75 at the time of risk score calculation is considered a minor criterion. The relevant time point for the calculation is the time of intervention (the PCI procedure, or shortly afterwords when therapy is being prescribed). 

=== Oral Anticoagulant Use

Anticipated use of long-term OAC is considered a major criterion. There are two types of oral anticoagulants:

* Vitamin K antagonists: warfarin
* Direct oral anticoagulants (DOAC): apixaban, dabigatran, edoxaban, rivaroxaban

"Anticipated long-term use" means that the patient is prescribed an OAC at the time of PCI, and a factor which indicates chronic use (for example, atrial fibrillation, or evidence of previous long-term use of OAC in previous prescribing history). Direct evidence of planned long-term use is also valid.

NOTE: As a crude approximation to the ARC HBR score, any prescription of warfarin or DOACs (regardless of "chronic use" awareness) could be taken to imply increased risk.

=== Chronic Kidney Disease

Severe or end-stage chronic kidney disease (CKD) is a major criterion; moderate CKD is a minor criterion.

The stages of chronic kidney disease map to both ICD-10 codes and estimated glomerular filtration rate measurements (eGFR, from urea and electrolytes laboratory results), as follows (see https://www.nhs.uk/conditions/kidney-disease/diagnosis/[here]):

[cols="1,1,1,1"]
|===
| Stage | ICD-10 | eGFR | ARC-HBR

| Stage 5, end-stage | N18.5 | eGFR < 15 ml/min | Major
| Stage 4, severe | N18.4 | 15 ml/min \<= eGFR < 30 ml/min | Major
| Stage 3b, moderate | N18.3 | 30 ml/min \<= eGFR < 45 ml/min | Minor
| Stage 3a, moderate | N18.3 | 45 ml/min \<= eGFR < 60 ml/min | Minor
| Stage 2, mild | N18.2 | 60 ml/min \<= eGFR < 90 ml/min | None
| Stage 1, normal eGFR | N18.1 | eGFR > 90 ml/min | None
|===

NOTE: Outside ARC HBR, temporal trends may be more predictive.

=== Anaemia (Low Haemoglobin)

Haemoglobin level < 11.0 g/dL is a major criterion (for men and women).

Haemoglobin (hb) greater than 11.0 g/dL is divided into two categories:

* Women: 11.0 g/dL \<= hb < 11.9 g/dL is a minor criterion
* Men: 11.0 g/dL \<= hb < 12.9 g/dL is a minor criterion

Any other haemoglobin level is not an ARC HBR criterion.

NOTE: In the ARC HBR official app, the anaemia calculation is simplified by using the Hb level for men for both men and women.

Haemoglobin level varies with time, and is captured in the data as either laboratory measurements from the full blood count, or potentially as anaemia codes from ICD-10 data in hospital episode statistics.

A blood test including an Hb measurement is often performed in the intervention episode, so this should be used to calculate the risk. If Hb from the index is not available, then a previous low Hb could be taken as a proxy to calculate the risk.

The anaemia HBR criterion has been interpreted to mean baseline anaemia (although this is not explicitly stated in the ARC HBR definition). As a result, the first Hb reading will be used to assess anaemia.

NOTE: An enhancement to the ARC HBR score may be achieved by considering time-varying Hb measurements. For example, a transient dip in Hb may reflect a heightened longterm risk of bleeding.

=== Prior Bleeding/Transfusion

The ARC HBR paper cite:[urban2019defining] states:

"Spontaneous (nonintracranial) bleeding requiring hospitalization or transfusion in the past 6 months (or at any time if recurrent) is considered a major ARC-HBR criterion, and a first spontaneous (nonintracranial) bleed requiring hospitalization or transfusion >6 and <12 months before PCI is considered a minor ARC-HBR criterion"
-- ARC HBR

Interpretation of terms:

* Spontaneous: not having an obvious cause (e.g. not due to trauma/major surgery).
* Recurrent: has occurred at least once before.

Summary of criteria:

* **Major**: Any bleed not in the brain within 6 months before PCI, which:
** Required hospitalisation (i.e. the hospitalisation was not due to something else) or required transfusion.
** Occurred on its own (i.e. was not caused by something else occurring in the spell, like other procedures)

* **Major** A non-first bleed (recurrent) occurring at any time, which satisfies the requirements above (hospitalisation/transfusion/spontaneous)

* **Minor** A first bleed _not_ within the 6 months before the PCI, which satisfies the requirements above (hospitalisation/transfusion/spontaneous)

NOTE: Previous work based on primary care data (system-wide dataset) indicated that any history of anaemia/bleeding (and therefore possible transfusion) was predictive of risk. Therefore, a crude form of ARC HBR calculation would be to take any previous bleeding diagnosis (e.g. from ICD-10 clinical coding) and use it as a proxy for this criterion, without considering spontaneity/recurrence. 

=== Thrombocytopenia (Low Platelet Count)

Moderate or severe baseline thrombocytopenia (low platelet count) i, meaning count < 100e9/L, is a major criterion.

Baseline means before intervention. The platelet count can be obtained from measurements from the full blood count. This information is routinely collected in the index presentation.

NOTE: Similarly to anaemia, time-varying behaviour of platelet count (e.g. transient dips) could prove more predictive for bleeding risk. In addition, considering the numerical value of the platelet count (e.g. considering 50e9/L as more severe than 90ep/L) could improve the score's performance.

=== Chronic Bleeding Diatheses

It is a major ARC criteria if any of these conditions are present at PCI:

* Platelet dysfunction; for example:
** von Willebrand disease
** Clotting factor deficiencies (including factors VII, VIII [hemophilia A], IX
[hemophilia B], and XI)
** Acquired antibodies to clotting factors

NOTE: There are many conditions which fall within the scope of this criterion; in addition, they are all quite rare. A crude indication of risk in this category may be that the patient has been seen by haemotology. 

=== Cirrhosis with Portal Hypertension

Presence of liver cirrhosis with portal hypertension is a major criterion. 

NOTE: THe ARC HBR official app states "liver cirrhosis" only on the main page of critera, but qualifies "with portal hypertension" on the next page. Applying the ARC HBR score strictly, liver cirrhosis alone is not an ARC criteria, but further granularity or predictivity in the score may be achievable by considering liver cirrhosis without portal hypertension to be a risk factor. Similarly, esophageal varices could also be considered in this category. 

=== Cancer

Diagnosis within the previous 12 months or ongoing active cancer treatment (surgery, radiotherapy, chemotherapy, immunotherapy) is a major ARC criterion.

=== Prior Ischaemic Stroke or ICH

The following are major ARC criteria:

* Brain arteriovenous malformation
* Prior intracranial haemorrhage at any time
* Prior moderate/severe ischaemic stroke (National Institutes of Health Stroke Scale >=5) within 6 months before PCI

The following is a minor criterion

* Prior ischaemic stroke (any severity, any time)

=== Planned Major Non-cardiac Surgery 

The ARC HBR paper cite:[urban2019defining] states:

"Planned nondeferrable [noncardiac] major surgery on DAPT after PCI is considered a major ARC-HBR criterion"
--- ARC HBR

Given the subjectivity around the use of the term "major surgery" cite:[newsome2021major], the following two approaches could be used to make an objective definition:

* Take all nondeferrable surgery on DAPT as a major risk criterion.
* Make a list of qualifying surgical procedures that confer major risk.

The timescale after PCI is not directly relevant; instead, the risk is related to with whether the patient will be on DAPT (which has a variable typical timescale after PCI, e.g. 3 - 6months). The calculation depends on a choice of DAPT, so this criteria cannot be calculated automatically based on patient characteristics/history.

=== Prior Major Surgery/Trauma 

Major surgery or major trauma within 30 days before PCI is a major ARC criterion. Similarly to the case of planned major surgery above, two approaches are possible:

* Consider any surgery or any trauma within the previous 30 days to confer major risk.
* Create a list of qualifying surgical procedures and trauma that confer major risk in the previous 30 days.

=== Long-term Oral NSAID/Steroid Use

Planned long-term use of oral NSAID/steriods at >= 4 days/week is a minor ARC criterion.

NOTE: Long-term use (similar to OAC) is not determined by the timescale. Instead, it is implied by an indication for chronic use combined with a prescription (i.e. if the patient has a condition that would imply they should be on long-term NSAID).
