= #Implementing Risk Scores on HIC Data#

This section describes implementations of the already-existing risk scores using data from the Hospital Information Collaborative (HIC) dataset, which is formed from finished consultant episode data, British Cardiovascular Intervention Society (BCIS) audit data from the BHI, and prescription information from the BHI.

Any score used in the deployed device must be validated using the data that will be used by the device. This data may have substantial overlap with the HIC data, meaning the results in this section may be indicative of the accuracy of the score calculated by the tool. However, for the purpose of making the clinical safety case (DCB 0129) for the device, the final selected score for the device should be validated on an extract of the same format of data used as input to the device.

== Overview of HIC data structure

The HIC dataset contains these six tables:

* `demographics`: Contains gender, year of birth and date of death.
* `episodes`: Contains an episode ID, and the episode start and end date/time.
* `diagnoses`: Contains all the diagnoses in an episode (linked by the episode ID); includes the diagnosis ICD-10 code, the diagnosis position, and the date/time of the diagnosis.
* `procedures`: Contains all the procedures in an episode (linked by the episode ID); includes the procedure OPCS-4 code, the procedure position, and the date/time of the procedure.
* `pathology_blood`: Contains blood test results, including the test result and unit; when the sample was collected/when the result was returned; and the normal range for the result. Tests are described using an `investigation` (e.g. full blood count) and a `test` within the investigation (e.g. platelets). Some tests/investigations relevant to the calculation of the ARC-HBR score are shown in <<blood_tests>>.
* `pharmacy_prescribing`: Contains prescriptions information, based on the discharge summary. The table contains the patient ID, the time of prescription, and whether the prescription was present on admission. The type of prescription information for some relevant medicines is shown in <<prescriptions>>.

.Relevant laboratory investigations/tests included in the blood tests table
[#blood_tests, format=csv, options="header"]
|===
include::relevant_blood_tests.csv[]
|===

.Relevant medicines contained in the prescriptions table and example data formats
[#prescriptions, format=csv, options="header"]
|===
include::example_prescriptions.csv[]
|===

=== Overview of Relevant Laboratory Tests

NOTE: TODO: put tables of all these investigations in this section to show all the available tests.

Some other laboratory investigations (i.e. classes of test) which may be relevant for bleeding are:

* LFT (liver function test)
* Clotting screen
* Serum ferritin (iron; bleeding results in a drop in iron)

Other full blood count tests relevant to bleeding:

* MCV (mean cell volume; bleeding tends to result in lower MCV)
* Haematocrit (proportion of red cells, lower after bleeding)

Relevant laboratory investigations for ischaemia risk:

* Diabetes (serrum glucose, glycosolated Hb (HbA1c)) 
* Cholesterol measurements come in different formats:
** Total cholesterol: this measurement returns just one value, which is the sum of all the cholesterol components.
** Non-HDL component only: HDH (high-density lipoprotein) is the "good" variety of cholesterol, so this measurement returns the total amount of "bad" cholesterol.
** Full profile: Each component is given separately: HDL, LDL (low-density lipoprotein), and triglycerides.
* Lipoprotein-a: Similar to LDL cholesterol

== ARC HBR Score Calculation

The ARC HBR score is the simplest possible calculation that would meet the intended purpose and provide value to clinicians selecting blood thinning medication for PCI patients. If it were used in the deployment, it would have the following advantages:

* Simple calculation and interpretation (compared to other approaches) as outlined in the ARC HBR paper
* Reduced validation requirement
** If the device also displays the raw information going into the score, the clinician can verify the calculation
** The score has been developed externally by clinical consensus
** The score has been externally validated (add the citations)
** The score makes a binary, rather than continuous, assessment of risk
* If the intended use of the device it to prompt the clinician to look closely at a particular patient, then the risk due to a false positive is that the clinician wastes time, and the risk due to a false negative is that the status quo (without the tool) is maintained. (There is a subtlety that a false negative may influence a clinician not to investigate a case they would previously have investigated. These cases will be analysed as part of the risk estimation.)

This section describes a calculation of the ARC HBR score using the HIC dataset, as a prototype which may inform the calculation in the final device.

Each criterion below can add 0, 0.5 or 1 to the total score.

=== Age

Age will be calculated using the episode start date (episodes table) and the year of birth (demographics table). The resulting age should be accurate to within about a year.

If age \> 75 years, 0.5 is added to the score.

=== Oral Anticoagulant Use

Presence of any of the following medications on admission (at the index ACS/PCI episode) will add 1 to the ARC HBR score:

* Warfarin
* Apixaban, rivaroxaban, edoxaban, dabigatran

#In a small sample of the HIC (2,379 index events), there are no OAC medicines on admission. There are 23 prescriptions of these drugs in total (presumably prescribed at index)#

NOTE: Dose is not considered in this implementation of the ARC HBR score.

== Chronic Kidney Disease

If a laboratory test for eGFR was taken during the index presentation #or at any time period before the index presentation#, use the result to calculate the contribution to the ARC score:

[cols="1,1"]
|===
| eGFR | Contribution to ARC-HBR

| < 15 mL/min | 1
| 15 mL/min \<= eGFR < 30 mL/min | 1
| 30 mL/min \<= eGFR < 60 mL/min | 0.5
|  >= 60 mL/min | 0
|===

#Approx. 25% of patients do not have an eGFR measurement in their index episode. Sounds quite high? Could be a programming error.#

If no eGFR result is available, fall back on presence of an ICD-10 code #at any time in patient history#:

[cols="1,1"]
|===
| ICD-10 | Contribution to ARC-HBR

| N18.5 | 1
| N18.4 | 1
| N18.3 | 0.5
| N18.2 | 0
| N18.1 | 0
|===

If no eGFR or clinical-code evidence of renal problems are present, assume ARC HBR 0.

=== Anaemia

Use the first Hb measurement from the index presentation for the purposes of the anaemia calculation. If no Hb measurement is present, use the most recent Hb measurement from the patient's medical history. Calculate the contribution to the ARC HBR score as follows (taking the first row that matches):

.Contribution to the ARC HBR score by Hb level/gender
[cols="1,1,1"]
|===
| Hb Level/(g/dL) | Male | Female
| < 11.0          | 1    | 1
| < 11.9          | 0.5  | 0.5
| < 12.9          | 0.5  | 0
| >= 12.9         | 0    | 0 
|===

If no Hb measurement is available in the patient history, fall back on ICD-10 codes:

#TODO put in the anaemia codes#

If no codes are present in the patient history, assume no ARC HBR criterion.

=== Prior Bleeding/Transfusion

Inclusion criteria for consideration of a bleeding event is:

* In the primary position (an attempt to capture "spontaneous"/not due to another cause)
* In the first episode of the spell (attempt to capture "requiring hospitalisation", i.e. the admission was due to the bleeding)

Depending on when the total number of qualifying events in the patient's history before the index ACS/PCI, the following rules are used (evaluate these conditions in order):

* If a bleed occurred 6 months before the index, add 1 to the ARC HBR score.
* If there are at least two bleeds in the patient history, add 1 to the ARC HBR score
* If there is only one bleed in the patient history, add 0.5 to the ARC HBR score
* If there are no bleeds in the patient history, add 0 to the ARC HBR score.

NOTE: Transfusion is ignored in this definition.

#The ICD-10 codes used to identify bleeding events are shown below#.

=== Thrombocytopenia (Low Platelet Count)

Using the first platelet count measurement from the index presentation, add 1 to the ARC HBR score if the count is <100e9/L. Otherwise add 0.

=== Chronic Bleeding Diatheses

TODO

=== Cirrhosis with Portal Hypertension

If the patient has any ICD-10 code for cirrhosis with portal hypertension at any point in their history, add 1 to the ARC HBR score. The relevant ICD-10 codes are shown below:

TODO CODES

=== Cancer

If the patient has a cancer diagnosis code (ICD-10) in the previous 12 months before the index ACS/PCI, add 1 to the ARC HBR score. The relevant ICD-10 codes are shown below:

TODO CODES

Alternatively, if the patient has ongoing cancer therapy (identified by OPCS-4 codes within 12 months before the diagnosis), then add 1 to the ARC HBR score. Relevant OPCS-4 codes are shown below:

NOTE: The ARC HBR definition refers to "ongoing" cancer therapy. The assumption is that a 12 month window should catch most ongoing therapy, but will also likely return some false positives (i.e. if therapy has just finished).

=== Prior Ischaemic Stroke or ICH

Add 1 to the ARC HBR score if either of these two conditions are present anywhere in the patient's history (ICD-10 codes):

* Brain arteriovenous malformation
* Prior intracranial haemorrhage at any time

The relevant codes are shown below:

Alternatively, identify all ischaemic stroke events in the patient's history, using ICD-10 codes:

* If a moderate/severe ischaemic stroke occurred within 6 months before ACS/PCI, then add 1 to the ARC HBR score; or
* If there is at least one ischaemic stroke, add 0.5 to the ARC HBR score

The relevant ICD-10 codes for ischaemic strokes, along with severity, are shown in the table below:

TODO CODES

=== Prior Major Non-cardiac Surgery

TODO

=== Prior Major Surgery/Trauma 

If there is any surgical procedure (OPCS-4 code) within 30 days before the index ACS/PCI presentation, add 1 to the ARC HBR score. Otherwise, add 0. Qualifying procedures are shown in the table below:

TODO CODES

=== Long-term Oral NSAID/Steroid Use

Presence of any of the following medications on admission (at the index ACS/PCI episode) where the frequency is >= 4 days/week will add 1 to the ARC HBR score:

* Ibuprofen
* Naproxen
* Diclofenac
* Celecoxib
* Mefenamic acid
* Etoricoxib
* Indomethacin
* Aspirin (high-dose, for pain-relief)
* #Anything else?#
