# #Implementing Risk Scores on HIC Data#

This section describes implementations of the already-existing risk scores using data from the Hospital Information Collaborative (HIC) dataset, which is formed from finished consultant episode data, British Cardiovascular Intervention Society (BCIS) audit data from the BHI, and prescription information from the BHI.

Any score used in the deployed device must be validated using the data that will be used by the device. This data may have substantial overlap with the HIC data, meaning the results in this section may be indicative of the accuracy of the score calculated by the tool. However, for the purpose of making the clinical safety case (DCB 0129) for the device, the final selected score for the device should be validated on an extract of the same format of data used as input to the device.

== Overview of HIC data structure

The HIC dataset contains these six tables:

* `demographics`: Contains gender, year of birth and date of death.
* `episodes`: Contains an episode ID, and the episode start and end date/time.
* `diagnoses`: Contains all the diagnoses in an episode (linked by the episode ID); includes the diagnosis ICD-10 code, the diagnosis position, and the date/time of the diagnosis.
* `procedures`: Contains all the procedures in an episode (linked by the episode ID); includes the procedure OPCS-4 code, the procedure position, and the date/time of the procedure.
* `pathology_blood`: Contains blood test results, including the test result and unit; when the sample was collected/when the result was returned; and the normal range for the result. Tests are described using an `investigation` (e.g. full blood count) and a `test` within the investigation (e.g. platelets). Some tests/investigations relevant to the calculation of the ARC-HBR score are shown in <<blood_tests>>.
* `pharmacy_prescribing`: Contains prescriptions information, based on the discharge summary. The table contains the patient ID, the time of prescription, and whether the prescription was present on admission. The type of prescription information for some relevant medicines is shown in <<prescriptions>>.

.Relevant laboratory investigations/tests included in the blood tests table
[#blood_tests, format=csv, options="header"]
|===
include::relevant_blood_tests.csv[]
|===

.Relevant medicines contained in the prescriptions table and example data formats
[#prescriptions, format=csv, options="header"]
|===
include::example_prescriptions.csv[]
|===

=== Overview of Relevant Laboratory Tests

NOTE: TODO: put tables of all these investigations in this section to show all the available tests.

Some other laboratory investigations (i.e. classes of test) which may be relevant for bleeding are:

* LFT (liver function test)
* Clotting screen
* Serum ferritin (iron; bleeding results in a drop in iron)

Other full blood count tests relevant to bleeding:

* MCV (mean cell volume; bleeding tends to result in lower MCV)
* Haematocrit (proportion of red cells, lower after bleeding)

Relevant laboratory investigations for ischaemia risk:

* Diabetes (serrum glucose, glycosolated Hb (HbA1c)) 
* Cholesterol measurements come in different formats:
** Total cholesterol: this measurement returns just one value, which is the sum of all the cholesterol components.
** Non-HDL component only: HDH (high-density lipoprotein) is the "good" variety of cholesterol, so this measurement returns the total amount of "bad" cholesterol.
** Full profile: Each component is given separately: HDL, LDL (low-density lipoprotein), and triglycerides.
* Lipoprotein-a: Similar to LDL cholesterol

== ARC HBR Score Calculation

The ARC HBR score is the simplest possible calculation that would meet the intended purpose and provide value to clinicians selecting blood thinning medication for PCI patients. If it were used in the deployment, it would have the following advantages:

* Simple calculation and interpretation (compared to other approaches) as outlined in the ARC HBR paper
* Reduced validation requirement
** If the device also displays the raw information going into the score, the clinician can verify the calculation
** The score has been developed externally by clinical consensus
** The score has been externally validated (add the citations)
** The score makes a binary, rather than continuous, assessment of risk
* If the intended use of the device it to prompt the clinician to look closely at a particular patient, then the risk due to a false positive is that the clinician wastes time, and the risk due to a false negative is that the status quo (without the tool) is maintained. (There is a subtlety that a false negative may influence a clinician not to investigate a case they would previously have investigated. These cases will be analysed as part of the risk estimation.)

This section describes a calculation of the ARC HBR score using the HIC dataset, as a prototype which may inform the calculation in the final device.

