= Weekly Notes

_This section will contain notes about progress this week, specific things to look at in this document (if any), etc._

Summary of previous week work (7th Feb - 13th Feb 2024):

* Accessed the new HIC testing data Mike gave me. 
** Written python code to access the tables and document the structure/made some notes on the blood test types/prescriptions.
** Just a few more technical things to get out the way, then should be able to start an ARC HBR score calculation!
* Got the GP opt-out finalised, sent off for first round of ICB approval.
* Looks like the national HES access is progressing a bit.

Actions for JS this week (13th Feb - 12th Feb 2024):

* Document specifically how to calculate ARC criteria from the HIC tables (including documenting code groups and calculation logic).
* Continue working on GP opt-out submission
* Continue working on national HES access form/logistics etc.
* Prepare a presentation for the BHI event next week -- going to do a talk on the dimension reduction work
* Start working on abstract for the ESC submission (end of Feb), also on dimension reduction work.

For Tom to look at:

* I've highlighted the new section on the HIC data tables/blood tests/prescriptions in yellow. Would you mind having a look through, and seeing if you think there are any big things missing? (e.g. other relevant drugs, or blood test categories). No need to comment/return, we can chat tomorrow and I can make notes.

