= Weekly Notes

_This section will contain notes about progress this week, specific things to look at in this document (if any), etc._

Summary of previous week work (23rd - 30th Jan 2024):

* Got comments back from Amy regarding the DPIA, started going through them. Plan to submit it after confirming a few details with Mike on Wednesday
* Started working on some of the required elements for the risk management file, with a view to contacting the IT team at UHBW in a few weeks for some advice on how we can integrate the tool within hospital systems.

Actions for JS this week (30th Jan - 6th Feb 2024):

* Meeting with Mike on Wednesday -- can hopefully get access to new HIC data (which will enable planning ARC HBR calculation)
* Submit DPIA to Amy after chatting to Mike
* Expect contract from UHBW

For Tom to look at:

* In the xref:preexisting_solutions.adoc#alternative_forms[Alternative Forms], you could have a read over the different proposed forms of the tool. I've tried to write up the different ideas, including the lab test integration idea Med and I discussed, the idea of developing new bespoke software, and the possibility of integrating into CCW. Feel free to add comments (but no need to do it before tomorrow!)

