= Risk Score Calculation and Validation

A variety of methods for calculating risk scores are under consideration for use in the tool. Potential options include:

* A simple calculation of whether the patient is at high bleeding risk using the ARC-HBR score (i.e. not including an assessment of ischaemia risk).
* Use of a statistical score for assessing bleeding/ischaemia risk, such as the PreciseDAPT score.
* Development of a custom statistical or machine-learning model to predict bleeding and ischaemia.

== Validation Prior to First Use

Any risk score, including those developed and validated externally, should be validated before use. This is because the implementation of the third-party risk calculation may contain difference compared with the original implementation that may effect the accuracy of the results; the intention is to establish that the predicted risks are not obviously wrong or unsafe.

Prior to initial (proof-of-principle) use, the validation must minimally involve testing that the risk predictions are valid on an internal dataset comprising:

* A sample of the data used as input into the tool (without modifications or processing)
* The patient outcome(s).

The risk score will be calculated for each patient in the dataset, and risk-score-specific accuracy criteria defined prior to performing the test will be used to establish that the score meets a minimum standard for use.

== Development of a Custom Model

The development of a custom model for bleeding/ischaemia is more complex than the use of a third-party score, because it requires development, initially lacks external validation, and initially lacks consideration/recommendation of the wider community.

On the other hand, a custom model offer better predictive performance, or be tailored better to the data available to the tool.

In addition to requiring the same minimal validation required before deployment of the external risk score, a training dataset (having the same format as the validation dataset) is required to develop the model and provide initial evidence that it works.

After the model has been developed, it should be assessed on a separate internal validation dataset (of the same kind as described above for third-party risk scores), to ensure it meets a minimal standard for use. However, the validation requirements should be more stringent than those for third-party externally-validated/already recommended scores.

In addition, initial use of the tool should be confined to the purposes of collecting data for further validation, and logging incidents (e.g. incorrect/odd-looking predictions), in order to build the safety case for the risk score.

== Patient Outcome Definition

In any validation of a high bleeding risk or bleeding/ischaemia risk score, numerical accuracy must be calculated with respect to some definition of bleeding/ischaemia outcomes.

These outcomes should be derived from expert clinical/academic consensus, in order to ensure that the risk score is calculating a relevant risk. 

This section contains a review of outcome definitions used in relation to other bleeding/ischaemia or cardiovascular scores, and which third-party scores use which outcome definitions.

TODO