= Clinical Risk Management Plan

WARNING: This plan is not yet approved (DCB 0129, section 3.2.2)

== Risk Acceptability Criteria

NOTE: The following risk definitions are taken from section 4.4 of the DCB 0129 guidance, with the intention to tailor them to this specific project.

Estimation of clinical risk involves:

* Estimating the severity of the hazard on a qualitative scale
* Estimating the likelihood of the hazard on a qualitative scale
* Use a matrix of likelihood and severity to obtain a clinical risk

The sections below describe the scales used for severity and likelihood, the matrix for obtaining a clinical risk, and the acceptability criteria for this risk.

=== Assessment of Severity

The following scale is used for the assessment of severity (terminology from DCB 0129 guidance document):

* *Minor*
** Affecting a single person
*** Minor injury from which recovery is expected in the short term; minor psychological upset; inconvenience; any negligible severity
* *Significant*
** If affecting a single person
*** Minor injury or injuries from which recovery is not expected in the short term; OR
*** Significant psychological trauma
** If affecting multiple people
*** Minor injury or injuries from which recovery is not expected in the short term; OR
*** Significant psychological trauma
* *Considerable* 
** If affecting a single person
*** Severe injury or severe incapacity from which recovery is expected in the short term; OR
*** Severe psychological trauma
** If affecting multiple people
*** Minor injury or injuries from which recovery is not expected in the short term.
*** Significant psychological trauma
* *Major* 
** If affecting a single person
*** Death; OR
*** Permanent life-changing incapacity and any condition for which the prognosis is death or permanent life-changing incapacity; severe injury or severe incapacity from which recovery is not expected in the short term
** If affecting multiple people
*** Severe injury or severe incapacity from which recovery is expected in the short term; OR
*** Severe psychological trauma
* *Catastrophic*
** Affecting multiple people:
*** Death; OR
*** Permanent life-changing incapacity and any condition for which the prognosis is death or permanent life-changing incapacity; severe injury or severe incapacity from which recovery is not expected in the short term

=== Assessment of Likelihood

The following scale is used for the assessment of severity (terminology from DCB 0129 guidance document):

* *Very high*: Certain or almost certain; highly likely to occur
* *High*: Not certain but very possible; reasonably expected to occur in the majority of cases
* *Medium*: Possible
* *Low*: Could occur but in the great majority of occasions will not
* *Very low*: Negligible or nearly negligible possibility of occurring

=== Risk Assessment Matrix

The following matrix (from DCB 0129 guidance document, Table 9) is used to obtain an clinical risk score for combinations of severity and likelihood:

.Clinical risks based on severity and likelihood of occurrence
[format=csv]
|===
include::risk_matrix.csv[]
|===

== Planned Activities

TODO
